version: "2.1"

services:
  frontend:
    build: client
    image: sciencespo/eatlas-frontend:latest
    links:
      - backend:backend
    ports:
      - 80:80
    volumes_from:
      - backend
    networks:
      - backend
    volumes:
      - uploadsdata:/eatlas/data/uploads:ro
  backend:
    build: .
    image: sciencespo/eatlas-backend:latest
    env_file:
      - docker-config.env
    environment:
      - SERVER_PORT=4000
      - SERVER_HOST=0.0.0.0
      - ES_HOST=es
      - ES_PORT=9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REACT_APP_MOCK_API=no
      - UPLOAD_PATH=/eatlas/data/uploads
      - CLIENT_PATH=/eatlas/data/uploads
    networks:
      - backend
      - es
      - redis
    links:
      - redis:redis
      - es:es
    volumes:
      - uploadsdata:/eatlas/data/uploads
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_image_types
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es

  redis:
    image: "redis:4.0.9"
    volumes:
      - redisdata:/data
    networks:
      - redis

networks:
  backend:
  es:
  redis:

volumes:
  esdata:
    driver: local
  redisdata:
    driver: local
  uploadsdata:
    driver: local
