version: "2.1"

services:

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_image_types
  es:
    container_name: eatlas_es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es

  redis:
    container_name: eatlas_redis
    image: "redis:4"
    volumes:
      - redisdata:/data
    networks:
      - redis

networks:
  es:
  redis:

volumes:
  esdata:
    driver: local
    name: eatlas_esdata
  redisdata:
    driver: local
    name: eatlas_redisdata
