version: "2"

services:

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_image_types
  es:
    container_name: eatlas_es
    #user: "${UID}:${GID}"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es

networks:
  es:

volumes:
  esdata:
    driver: local
